### PR TITLE
us1

### PR DESCRIPTION
**Pull request by ozturkkerem**
US 1 test case

### CODE REVIEW

**Review by magdalenagru91 — APPROVED** [review]
Looks good

**Review by FarangisB — APPROVED** [review]
Good job

**Comment by Farangez** [comment]
looks good

**Review by Farangez — APPROVED** [review]
good job!

**Review by Farangez — APPROVED** [review]

**Review by Farangez — APPROVED** [review]

**Review by FarangisB — APPROVED** [review]
Good job

**Review by ozturkkerem — COMMENTED** [review]
ok

**Review by ozturkkerem — COMMENTED** [review]
k

**Review by ozturkkerem — COMMENTED** [review]
ok

**Review by ozturkkerem — COMMENTED** [review]
xx

**Pull request merged**
